<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Command.Demo</AssemblyName>
    <RootNamespace>dev.kaldiroglu.Command.Demo</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Command\Command.csproj" />
  </ItemGroup>

</Project>
