<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Mediator.Demo</AssemblyName>
    <RootNamespace>dev.kaldiroglu.Mediator.Demo</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mediator\Mediator.csproj" />
  </ItemGroup>

</Project>
